#!/bin/bash

BATS_TAG=v0.4.0
RBENV_TAG=v1.0.0

git clone --depth 1 --branch $BATS_TAG https://github.com/sstephenson/bats.git
PATH="$PWD/bats/bin:$PATH"

git clone --depth 1 --branch $RBENV_TAG https://github.com/sstephenson/rbenv.git
PATH="$PWD/rbenv/bin:$PATH"

exec bats ${CI:+--tap} test/"$1"
